ekf_filter_node:
    ros__parameters:
        frequency: 
        two_d_mode: 
        publish_acceleration: 
        publish_tf: 

        map_frame:        
        odom_frame:        
        base_link_frame: 
        world_frame:  

        odom0: odom/unfiltered
        odom0_config: [false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false,
                       false, false, false]

        imu0: imu/data
        imu0_config: [false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, false,
                      false, false, false]