<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="Oni_Claw">
    <xacro:include filename="sensors/imu_sensor.urdf.xacro"/>
    <xacro:include filename="sensors/laser_sensor.urdf.xacro"/>
    <xacro:include filename="controller/omni_drive.urdf.xacro"/>

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_width" value="0.026"/>
    <xacro:property name="wheel_xoff" value="0.05"/>
    <xacro:property name="wheel_yoff" value="0.085"/>
    <xacro:property name="wheel_zoff" value="-0.014"/>
    <xacro:property name="wheel_mass" value="0.3"/>

    <xacro:macro name="mecanum_wheel" params="side x_reflect y_reflect orientation_z mesh">
        <link name="${side}_wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${orientation_z}"/>
            <geometry>
            <mesh filename="${mesh}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${(2/5) * wheel_mass * (wheel_radius * wheel_radius)}" ixy="0" ixz="0"
                    iyy="${(2/5) * wheel_mass * (wheel_radius * wheel_radius)}" iyz="0"
                    izz="${(2/5) * wheel_mass * (wheel_radius * wheel_radius)}" />
        </inertial>
        </link>

        <gazebo reference="${side}_wheel_link">
            <mu1>0.01</mu1>
            <mu2>0.01</mu2>
        </gazebo>

        <joint name="${side}_wheel_to_base_link" type="continuous">
        <axis xyz="1 0 0" />
        <parent link="base_link"/>
        <child link="${side}_wheel_link"/>
        <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * wheel_yoff} ${wheel_zoff}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <link name="base_footprint"/>
    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-wheel_radius - wheel_zoff}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 -${pi/2}"/>
            <geometry>
                <mesh filename="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/body_OC.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 -${pi/2}"/>
            <geometry>
                <mesh filename="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/body_OC.dae"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.8"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.0029" ixy="0.0" ixz="0.0" iyy="0.0029" iyz="0.0" izz="0.00533"/>
        </inertial>
    </link>

    <xacro:mecanum_wheel
        side="front_right"
        x_reflect="1"
        y_reflect="-1"    
        orientation_z="${pi/2}"
        mesh="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/fr_wheel.dae"
    />

    <xacro:mecanum_wheel
        side="front_left"
        x_reflect="1"
        y_reflect="1"  
        orientation_z="${-pi/2}"
        mesh="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/fl_wheel.dae"
    />

    <xacro:mecanum_wheel
        side="back_right"
        x_reflect="-1"
        y_reflect="-1"  
        orientation_z="${pi/2}"
        mesh="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/fr_wheel.dae"
    />

    <xacro:mecanum_wheel
        side="back_left"
        x_reflect="-1"
        y_reflect="1"  
        orientation_z="${-pi/2}"
        mesh="file:///$(find ugv_robots_description)/robot_description/meshes/oni_meshes/fl_wheel.dae"
    />

    <xacro:imu_sensor/>

    <xacro:laser_sensor
        update_rate="5"
        ray_count="360"
        min_angle="0"
        max_angle="6.28"
        min_range="0.12"
        max_range="8.0"
        frame_id="lidar_link"
        topic_name="scan"
    />

    <xacro:omni_drive_controller/>
</robot>